{
 "title": "Niro EV",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "High voltage Battery SoC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "select unix_last_vehicle_update_timestamp, battery_percentage, ac_charge_limit_percent, dc_charge_limit_percent from log;",
     "rawQueryText": "select unix_last_vehicle_update_timestamp, battery_percentage, ac_charge_limit_percent, dc_charge_limit_percent from log;",
     "timeColumns": [
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Estimated range (km)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "select unix_last_vehicle_update_timestamp, estimated_range_km from log;",
     "rawQueryText": "select unix_last_vehicle_update_timestamp, estimated_range_km from log;",
     "timeColumns": [
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  },
  {
   "title": "12v Battery SoC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "select unix_last_vehicle_update_timestamp, accessory_battery_percentage from log;",
     "rawQueryText": "select unix_last_vehicle_update_timestamp, accessory_battery_percentage from log;",
     "timeColumns": [
      "time",
      "ts",
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Estimated Charging Power (kW)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "select unix_last_vehicle_update_timestamp, rough_charging_power_estimate_kw from log;",
     "rawQueryText": "select unix_last_vehicle_update_timestamp, rough_charging_power_estimate_kw from log;",
     "timeColumns": [
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Climate control power usage (% of total)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "select unix_timestamp, climate_consumption_kwh / total_consumed_kwh * 100 as climate_power_usage_percentage_of_total\nfrom stats_per_day\nwhere engine_consumption_kwh > 0;",
     "rawQueryText": "select unix_timestamp, climate_consumption_kwh / total_consumed_kwh * 100 as climate_power_usage_percentage_of_total\nfrom stats_per_day\nwhere engine_consumption_kwh > 0;",
     "timeColumns": [
      "time",
      "ts",
      "unix_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Charge status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "queryText": "select unix_last_vehicle_update_timestamp, charging from log;",
     "rawQueryText": "select unix_last_vehicle_update_timestamp, charging from log;",
     "timeColumns": [
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Power usage vs. Regen (kWh)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "select unix_timestamp, -total_consumed_kwh, regenerated_energy_kwh\nfrom stats_per_day;",
     "rawQueryText": "select unix_timestamp, -total_consumed_kwh, regenerated_energy_kwh\nfrom stats_per_day;",
     "timeColumns": [
      "time",
      "ts",
      "unix_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Odometer (km)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select odometer, unix_last_vehicle_update_timestamp from log;",
     "rawQueryText": "select odometer, unix_last_vehicle_update_timestamp from log;",
     "timeColumns": [
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Battery SoC",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select battery_percentage from log\norder by unix_timestamp desc\nlimit 1\n;",
     "rawQueryText": "select battery_percentage from log\norder by unix_timestamp desc\nlimit 1\n;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "queryText": "select unix_timestamp, exc_type from errors;",
     "rawQueryText": "select unix_timestamp, exc_type from errors;",
     "timeColumns": [ "unix_timestamp" ]
    }
   ]
  },
  {
   "title": "Target HVAC temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "select unix_last_vehicle_update_timestamp, target_climate_temperature\nfrom log;",
     "rawQueryText": "select unix_last_vehicle_update_timestamp, target_climate_temperature\nfrom log;",
     "timeColumns": [
      "unix_last_vehicle_update_timestamp"
     ]
    }
   ]
  }
 ]
}